### ISSUE TITLE
Add Python Node

### ISSUE THREAD

**Issue by hunnybear** [FlowCV-org/FlowCV#1]
During a conversation with Richard, we discussed creating a Python node, which should embed Python, and allow for using Python code either directly stored in the node, or referenced by file name.

**Comment by hunnybear** [comment]
I intend to work on this myself, Just creating an issue so that it can be tracked

**Comment by rwardlow01** [comment]
Experimental python node plugin is finished - https://github.com/FlowCV-org/FlowCV_Python
See repo README for more info
