### ISSUE TITLE
Ui Bug in Customize Section of Columns : width is not inside the parent div

### ISSUE THREAD

**Issue by omhari1472** [FlowCV-org/FlowCV#16]
<img width="1440" alt="Screenshot 2024-09-07 at 8 22 13 PM" src="https://github.com/user-attachments/assets/8e87cb0c-20cd-46b0-b7a9-736a9a3582f7">

**Comment by omhari1472** [comment]
Hi team,

I wanted to follow up on the UI bug in the Customize Section of Columns (#16), where the width is not contained within the parent div. As a user of your platform, this issue affects the layout, and I would really appreciate it if it could be addressed.

I’m just a beginner, but I’d love to help out where I can, even if it’s just contributing to the fix. Please let me know if that’s possible or if you need any further information from my side!

Thanks for your time and for the great work on the platform!

**Comment by rwardlow01** [comment]
You are posting this to the wrong repo, this repo is FlowCV (www.flowcv.org) it is a node based computer vision processing application and has nothing to do with app.flowcv.com
