### ISSUE TITLE
error LNK2001 cv::dnn::dnn4_v20220524::Net::setInput (0.2.0 Windows)

### ISSUE THREAD

**Issue by zmoth** [FlowCV-org/FlowCV#8]
In the latest version 0.2.0 opencv's dnn is not linked in some versions. Make a marker note here.

* opencv-4.5.5-openvino-dldt-2021.4.2-vc16-avx2
Download https://github.com/opencv/opencv/releases/download/4.5.5/opencv-4.5.5-openvino-dldt-2021.4.2-vc16-avx2.7z
**Release: √**
**RelWithDebInfo: √**

* opencv-4.5.5-openvino-dldt-2021.4.2-vc16-avx2-debug
Download https://github.com/opencv/opencv/releases/download/4.5.5/opencv-4.5.5-openvino-dldt-2021.4.2-vc16-avx2-debug.7z
**Debug: ×**

*  opencv-4.7.0
I compiled opencv 4.7.0 myself. 
**Release: √**
**RelWithDebInfo: √**
**Debug: ×**

Does this project have to have openvino for the use of opencv? We should probably restrict the version of opencv in READEME

```
[build] dnn_segmentation.obj : error LNK2001: 无法解析的外部符号 "public: void __cdecl cv::dnn::dnn4_v20220524::Net::setInput(class cv::debug_build_guard::_InputArray const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,double,class cv::Scalar_<double> const &)" (?setInput@Net@dnn4_v20220524@dnn@cv@@QEAAXAEBV_InputArray@debug_build_guard@4@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@NAEBV?$Scalar_@N@4@@Z) [D:\proj\FlowCV\build\Editor_UI\FlowCV_Editor.vcxproj]
[build] dnn_human_pose.obj : error LNK2001: 无法解析的外部符号 "public: void __cdecl cv::dnn::dnn4_v20220524::Net::setInput(class cv::debug_build_guard::_InputArray const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,double,class cv::Scalar_<double> const &)" (?setInput@Net@dnn4_v20220524@dnn@cv@@QEAAXAEBV_InputArray@debug_build_guard@4@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@NAEBV?$Scalar_@N@4@@Z) [D:\proj\FlowCV\build\Editor_UI\FlowCV_Editor.vcxproj]
```

**Comment by rwardlow01** [comment]
Yeah, unfortunately for some reason on those pre-compiled releases of OpenCV they don't include all of the debug libraries in one archive, I'll need to make some changes to the CMake build file to handle different archives for release vs debug, in the meantime you can use release with debug info if you need to run FlowCV and debug and set break points.

**Comment by zmoth** [comment]
Thanks for the explanation, for the time being I can use this method to debug.
As a follow up, do we need to explain how to compile opencv in order to get this project to work?

such as:
```bash
git clone https://github.com/opencv/opencv.git
git checkout 4.5.5-openvino-2022.1.0
git clone https://github.com/opencv/opencv_contrib.git
git checkout 4.5.5

cd opencv
makedir build
cd build
cmake ......
```
Or we can provide our own compiled and tested opencv packages.

**Comment by rwardlow01** [comment]
Currently on windows it's using the pre-compiled build of OpenCV with OpenVino from the github releases file.

On Linux and MacOS it's using the OpenVino installer and pre-compiled OpenCV build from the OpenCV installer script provided by OpenVino, I've updated the "Building From Source" documentation pages with the instructions.

If someone wants to build their own OpenCV from source and use it with FlowCV then they probably know what their doing and should be able to figure things out. There's also plenty of documentation out there on how to build OpenCV from source.

OpenVino is not required, I haven't tried building the latest OpenCV from source yet, perhaps they have some default flag set that is looking for or expecting OpenVino? As long as the OpenCV version being built comes with the DNN module and there haven't been any major changes from version 4.5.5 that would break DNN compatibility then I assume it should work.

**Comment by zmoth** [comment]
Thanks, I should understand after reading your explanation. I don't know much about openvino and I don't have a linux system to use for testing. If I get a chance, I will try to compile it on different platforms.
